<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Document Principal</title>
</head>
<body>
   <nav>
      <a href="index.php">Accueil</a>
      <a href="index.php">Categorie</a>
   </nav>
   
   <main>
      <?php include $template ?>
   </main>
         
</body>
</html>
